version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432"

  backend:
    container_name: fastapi
    depends_on:
      - postgres
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: [ "/code/docker/alembic.sh" ]





